#ifdef AVX_512
#ifndef __HOST_AVX512_H
#define __HOST_AVX512_H

/* This file is auto-generated by "filegen" script */
/* DO NOT MODIFY */

/*
   This file is part of Valgrind, a dynamic binary instrumentation
   framework.

   Copyright (C) 2021 Intel Corporation 
      tatyana.a.volnina@intel.com

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License as
   published by the Free Software Foundation; either version 2 of the
   License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, see <http://www.gnu.org/licenses/>.

   The GNU General Public License is contained in the file COPYING.
*/

#include <host_generic_simd64.h>
#include <host_amd64_defs.h>
#include <host_generic_AVX512.h>

typedef struct {
   char* name;
   const void* function_call;
   const IRType operands[5]; // in most cases, Intel syntax: dst, src1, src2,..
}
Iop_data;

#define INDEX(ir) ((ir)-Iop_FIRST_EVEX)
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdiscarded-qualifiers"
#endif
static const Iop_data IOPS_ARR[] = {
   /*     OPCODE IRs          { text name | function | operands (Intel syntax) } */
	[ INDEX (Iop_RoundScale32x16)]	= {"Iop_RoundScale32x16", h_Iop_RoundScale32x16, {Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_RoundScale64x8)]	= {"Iop_RoundScale64x8", h_Iop_RoundScale64x8, {Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_RoundScale32F0x4)]	= {"Iop_RoundScale32F0x4", h_Iop_RoundScale32F0x4, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_RoundScale64F0x2)]	= {"Iop_RoundScale64F0x2", h_Iop_RoundScale64F0x2, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Perm32x16)]	= {"Iop_Perm32x16", h_Iop_Perm32x16, {Ity_V512,Ity_V512,Ity_V512}},
	[ INDEX (Iop_Perm64x4)]	= {"Iop_Perm64x4", h_Iop_Perm64x4, {Ity_V256,Ity_V256,Ity_V256}},
	[ INDEX (Iop_Perm64x8)]	= {"Iop_Perm64x8", h_Iop_Perm64x8, {Ity_V512,Ity_V512,Ity_V512}},
	[ INDEX (Iop_Cmp32Ux4)]	= {"Iop_Cmp32Ux4", h_Iop_Cmp32Ux4, {Ity_I64,Ity_I64,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Cmp32Ux8)]	= {"Iop_Cmp32Ux8", h_Iop_Cmp32Ux8, {Ity_I64,Ity_I64,Ity_V256,Ity_V256,Ity_I8}},
	[ INDEX (Iop_Cmp32Ux16)]	= {"Iop_Cmp32Ux16", h_Iop_Cmp32Ux16, {Ity_I64,Ity_I64,Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_Cmp64Ux2)]	= {"Iop_Cmp64Ux2", h_Iop_Cmp64Ux2, {Ity_I64,Ity_I64,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Cmp64Ux4)]	= {"Iop_Cmp64Ux4", h_Iop_Cmp64Ux4, {Ity_I64,Ity_I64,Ity_V256,Ity_V256,Ity_I8}},
	[ INDEX (Iop_Cmp64Ux8)]	= {"Iop_Cmp64Ux8", h_Iop_Cmp64Ux8, {Ity_I64,Ity_I64,Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_Cmp32Sx4)]	= {"Iop_Cmp32Sx4", h_Iop_Cmp32Sx4, {Ity_I64,Ity_I64,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Cmp32Sx8)]	= {"Iop_Cmp32Sx8", h_Iop_Cmp32Sx8, {Ity_I64,Ity_I64,Ity_V256,Ity_V256,Ity_I8}},
	[ INDEX (Iop_Cmp32Sx16)]	= {"Iop_Cmp32Sx16", h_Iop_Cmp32Sx16, {Ity_I64,Ity_I64,Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_Cmp64Sx2)]	= {"Iop_Cmp64Sx2", h_Iop_Cmp64Sx2, {Ity_I64,Ity_I64,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Cmp64Sx4)]	= {"Iop_Cmp64Sx4", h_Iop_Cmp64Sx4, {Ity_I64,Ity_I64,Ity_V256,Ity_V256,Ity_I8}},
	[ INDEX (Iop_Cmp64Sx8)]	= {"Iop_Cmp64Sx8", h_Iop_Cmp64Sx8, {Ity_I64,Ity_I64,Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_16Sto8x8)]	= {"Iop_16Sto8x8", h_Iop_16Sto8x8, {Ity_I64,Ity_V128}},
	[ INDEX (Iop_Ternlog32x16)]	= {"Iop_Ternlog32x16", h_Iop_Ternlog32x16, {Ity_V512,Ity_V512,Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_Ternlog64x8)]	= {"Iop_Ternlog64x8", h_Iop_Ternlog64x8, {Ity_V512,Ity_V512,Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_Test8x16)]	= {"Iop_Test8x16", h_Iop_Test8x16, {Ity_I64,Ity_I64,Ity_V128,Ity_V128}},
	[ INDEX (Iop_Test8x32)]	= {"Iop_Test8x32", h_Iop_Test8x32, {Ity_I64,Ity_I64,Ity_V256,Ity_V256}},
	[ INDEX (Iop_Test8x64)]	= {"Iop_Test8x64", h_Iop_Test8x64, {Ity_I64,Ity_I64,Ity_V512,Ity_V512}},
	[ INDEX (Iop_Test16x8)]	= {"Iop_Test16x8", h_Iop_Test16x8, {Ity_I64,Ity_I64,Ity_V128,Ity_V128}},
	[ INDEX (Iop_Test16x16)]	= {"Iop_Test16x16", h_Iop_Test16x16, {Ity_I64,Ity_I64,Ity_V256,Ity_V256}},
	[ INDEX (Iop_Test16x32)]	= {"Iop_Test16x32", h_Iop_Test16x32, {Ity_I64,Ity_I64,Ity_V512,Ity_V512}},
	[ INDEX (Iop_GetMant32x16)]	= {"Iop_GetMant32x16", h_Iop_GetMant32x16, {Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_GetMant64x8)]	= {"Iop_GetMant64x8", h_Iop_GetMant64x8, {Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_TestN8x16)]	= {"Iop_TestN8x16", h_Iop_TestN8x16, {Ity_I64,Ity_I64,Ity_V128,Ity_V128}},
	[ INDEX (Iop_TestN8x32)]	= {"Iop_TestN8x32", h_Iop_TestN8x32, {Ity_I64,Ity_I64,Ity_V256,Ity_V256}},
	[ INDEX (Iop_TestN8x64)]	= {"Iop_TestN8x64", h_Iop_TestN8x64, {Ity_I64,Ity_I64,Ity_V512,Ity_V512}},
	[ INDEX (Iop_TestN16x8)]	= {"Iop_TestN16x8", h_Iop_TestN16x8, {Ity_I64,Ity_I64,Ity_V128,Ity_V128}},
	[ INDEX (Iop_TestN16x16)]	= {"Iop_TestN16x16", h_Iop_TestN16x16, {Ity_I64,Ity_I64,Ity_V256,Ity_V256}},
	[ INDEX (Iop_TestN16x32)]	= {"Iop_TestN16x32", h_Iop_TestN16x32, {Ity_I64,Ity_I64,Ity_V512,Ity_V512}},
	[ INDEX (Iop_Test32x4)]	= {"Iop_Test32x4", h_Iop_Test32x4, {Ity_I64,Ity_I64,Ity_V128,Ity_V128}},
	[ INDEX (Iop_Test32x8)]	= {"Iop_Test32x8", h_Iop_Test32x8, {Ity_I64,Ity_I64,Ity_V256,Ity_V256}},
	[ INDEX (Iop_Test32x16)]	= {"Iop_Test32x16", h_Iop_Test32x16, {Ity_I64,Ity_I64,Ity_V512,Ity_V512}},
	[ INDEX (Iop_Test64x2)]	= {"Iop_Test64x2", h_Iop_Test64x2, {Ity_I64,Ity_I64,Ity_V128,Ity_V128}},
	[ INDEX (Iop_Test64x4)]	= {"Iop_Test64x4", h_Iop_Test64x4, {Ity_I64,Ity_I64,Ity_V256,Ity_V256}},
	[ INDEX (Iop_Test64x8)]	= {"Iop_Test64x8", h_Iop_Test64x8, {Ity_I64,Ity_I64,Ity_V512,Ity_V512}},
	[ INDEX (Iop_GetMant32F0x4)]	= {"Iop_GetMant32F0x4", h_Iop_GetMant32F0x4, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_GetMant64F0x2)]	= {"Iop_GetMant64F0x2", h_Iop_GetMant64F0x2, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_TestN32x4)]	= {"Iop_TestN32x4", h_Iop_TestN32x4, {Ity_I64,Ity_I64,Ity_V128,Ity_V128}},
	[ INDEX (Iop_TestN32x8)]	= {"Iop_TestN32x8", h_Iop_TestN32x8, {Ity_I64,Ity_I64,Ity_V256,Ity_V256}},
	[ INDEX (Iop_TestN32x16)]	= {"Iop_TestN32x16", h_Iop_TestN32x16, {Ity_I64,Ity_I64,Ity_V512,Ity_V512}},
	[ INDEX (Iop_TestN64x2)]	= {"Iop_TestN64x2", h_Iop_TestN64x2, {Ity_I64,Ity_I64,Ity_V128,Ity_V128}},
	[ INDEX (Iop_TestN64x4)]	= {"Iop_TestN64x4", h_Iop_TestN64x4, {Ity_I64,Ity_I64,Ity_V256,Ity_V256}},
	[ INDEX (Iop_TestN64x8)]	= {"Iop_TestN64x8", h_Iop_TestN64x8, {Ity_I64,Ity_I64,Ity_V512,Ity_V512}},
	[ INDEX (Iop_ExpandBitsToV128)]	= {"Iop_ExpandBitsToV128", h_Iop_ExpandBitsToV128, {Ity_V128,Ity_I64,Ity_I8}},
	[ INDEX (Iop_ExpandBitsToV256)]	= {"Iop_ExpandBitsToV256", h_Iop_ExpandBitsToV256, {Ity_V256,Ity_I64,Ity_I8}},
	[ INDEX (Iop_ExpandBitsToV512)]	= {"Iop_ExpandBitsToV512", h_Iop_ExpandBitsToV512, {Ity_V512,Ity_I64,Ity_I8}},
	[ INDEX (Iop_Scale32x16)]	= {"Iop_Scale32x16", h_Iop_Scale32x16, {Ity_V512,Ity_V512,Ity_V512}},
	[ INDEX (Iop_Scale64x8)]	= {"Iop_Scale64x8", h_Iop_Scale64x8, {Ity_V512,Ity_V512,Ity_V512}},
	[ INDEX (Iop_Scale32F0x4)]	= {"Iop_Scale32F0x4", h_Iop_Scale32F0x4, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_Scale64F0x2)]	= {"Iop_Scale64F0x2", h_Iop_Scale64F0x2, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_Min64Sx8)]	= {"Iop_Min64Sx8", h_Iop_Min64Sx8, {Ity_V512,Ity_V512,Ity_V512}},
	[ INDEX (Iop_Min64Ux8)]	= {"Iop_Min64Ux8", h_Iop_Min64Ux8, {Ity_V512,Ity_V512,Ity_V512}},
	[ INDEX (Iop_Max64Sx8)]	= {"Iop_Max64Sx8", h_Iop_Max64Sx8, {Ity_V512,Ity_V512,Ity_V512}},
	[ INDEX (Iop_Cmp8Ux16)]	= {"Iop_Cmp8Ux16", h_Iop_Cmp8Ux16, {Ity_I64,Ity_I64,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Cmp8Ux32)]	= {"Iop_Cmp8Ux32", h_Iop_Cmp8Ux32, {Ity_I64,Ity_I64,Ity_V256,Ity_V256,Ity_I8}},
	[ INDEX (Iop_Cmp8Ux64)]	= {"Iop_Cmp8Ux64", h_Iop_Cmp8Ux64, {Ity_I64,Ity_I64,Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_Cmp16Ux8)]	= {"Iop_Cmp16Ux8", h_Iop_Cmp16Ux8, {Ity_I64,Ity_I64,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Cmp16Ux16)]	= {"Iop_Cmp16Ux16", h_Iop_Cmp16Ux16, {Ity_I64,Ity_I64,Ity_V256,Ity_V256,Ity_I8}},
	[ INDEX (Iop_Cmp16Ux32)]	= {"Iop_Cmp16Ux32", h_Iop_Cmp16Ux32, {Ity_I64,Ity_I64,Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_Cmp8Sx16)]	= {"Iop_Cmp8Sx16", h_Iop_Cmp8Sx16, {Ity_I64,Ity_I64,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Cmp8Sx32)]	= {"Iop_Cmp8Sx32", h_Iop_Cmp8Sx32, {Ity_I64,Ity_I64,Ity_V256,Ity_V256,Ity_I8}},
	[ INDEX (Iop_Cmp8Sx64)]	= {"Iop_Cmp8Sx64", h_Iop_Cmp8Sx64, {Ity_I64,Ity_I64,Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_Cmp16Sx8)]	= {"Iop_Cmp16Sx8", h_Iop_Cmp16Sx8, {Ity_I64,Ity_I64,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Cmp16Sx16)]	= {"Iop_Cmp16Sx16", h_Iop_Cmp16Sx16, {Ity_I64,Ity_I64,Ity_V256,Ity_V256,Ity_I8}},
	[ INDEX (Iop_Cmp16Sx32)]	= {"Iop_Cmp16Sx32", h_Iop_Cmp16Sx32, {Ity_I64,Ity_I64,Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_Max64Ux8)]	= {"Iop_Max64Ux8", h_Iop_Max64Ux8, {Ity_V512,Ity_V512,Ity_V512}},
	[ INDEX (Iop_ExtractExp32x16)]	= {"Iop_ExtractExp32x16", h_Iop_ExtractExp32x16, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_ExtractExp64x8)]	= {"Iop_ExtractExp64x8", h_Iop_ExtractExp64x8, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_VDBPSADBW)]	= {"Iop_VDBPSADBW", h_Iop_VDBPSADBW, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_ExtractExp32F0x4)]	= {"Iop_ExtractExp32F0x4", h_Iop_ExtractExp32F0x4, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_ExtractExp64F0x2)]	= {"Iop_ExtractExp64F0x2", h_Iop_ExtractExp64F0x2, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_Recip14_32x16)]	= {"Iop_Recip14_32x16", h_Iop_Recip14_32x16, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_Recip14_64x8)]	= {"Iop_Recip14_64x8", h_Iop_Recip14_64x8, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_Recip14_32F0x4)]	= {"Iop_Recip14_32F0x4", h_Iop_Recip14_32F0x4, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_Recip14_64F0x2)]	= {"Iop_Recip14_64F0x2", h_Iop_Recip14_64F0x2, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_RSqrt14_32x16)]	= {"Iop_RSqrt14_32x16", h_Iop_RSqrt14_32x16, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_RSqrt14_64x8)]	= {"Iop_RSqrt14_64x8", h_Iop_RSqrt14_64x8, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_RSqrt14_32F0x4)]	= {"Iop_RSqrt14_32F0x4", h_Iop_RSqrt14_32F0x4, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_RSqrt14_64F0x2)]	= {"Iop_RSqrt14_64F0x2", h_Iop_RSqrt14_64F0x2, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_Range32x4)]	= {"Iop_Range32x4", h_Iop_Range32x4, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Range64x2)]	= {"Iop_Range64x2", h_Iop_Range64x2, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_DPBUSD)]	= {"Iop_DPBUSD", h_Iop_DPBUSD, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_Range32F0x4)]	= {"Iop_Range32F0x4", h_Iop_Range32F0x4, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Range64F0x2)]	= {"Iop_Range64F0x2", h_Iop_Range64F0x2, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_DPBUSDS)]	= {"Iop_DPBUSDS", h_Iop_DPBUSDS, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_DPWSSD)]	= {"Iop_DPWSSD", h_Iop_DPWSSD, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_DPWSSDS)]	= {"Iop_DPWSSDS", h_Iop_DPWSSDS, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_FixupImm32x16)]	= {"Iop_FixupImm32x16", h_Iop_FixupImm32x16, {Ity_V512,Ity_V512,Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_FixupImm64x8)]	= {"Iop_FixupImm64x8", h_Iop_FixupImm64x8, {Ity_V512,Ity_V512,Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_PopCount8x16)]	= {"Iop_PopCount8x16", h_Iop_PopCount8x16, {Ity_V128,Ity_V128}},
	[ INDEX (Iop_FixupImm32F0x4)]	= {"Iop_FixupImm32F0x4", h_Iop_FixupImm32F0x4, {Ity_V128,Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_FixupImm64F0x2)]	= {"Iop_FixupImm64F0x2", h_Iop_FixupImm64F0x2, {Ity_V128,Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Reduce32x4)]	= {"Iop_Reduce32x4", h_Iop_Reduce32x4, {Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Reduce64x2)]	= {"Iop_Reduce64x2", h_Iop_Reduce64x2, {Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Reduce32F0x4)]	= {"Iop_Reduce32F0x4", h_Iop_Reduce32F0x4, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Reduce64F0x2)]	= {"Iop_Reduce64F0x2", h_Iop_Reduce64F0x2, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Compress8x16)]	= {"Iop_Compress8x16", h_Iop_Compress8x16, {Ity_V128,Ity_V128}},
	[ INDEX (Iop_Compress16x8)]	= {"Iop_Compress16x8", h_Iop_Compress16x8, {Ity_V128,Ity_V128}},
	[ INDEX (Iop_Classify32x4)]	= {"Iop_Classify32x4", h_Iop_Classify32x4, {Ity_I64,Ity_I64,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Classify32x8)]	= {"Iop_Classify32x8", h_Iop_Classify32x8, {Ity_I64,Ity_I64,Ity_V256,Ity_I8}},
	[ INDEX (Iop_Classify32x16)]	= {"Iop_Classify32x16", h_Iop_Classify32x16, {Ity_I64,Ity_I64,Ity_V512,Ity_I8}},
	[ INDEX (Iop_Classify64x2)]	= {"Iop_Classify64x2", h_Iop_Classify64x2, {Ity_I64,Ity_I64,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Classify64x4)]	= {"Iop_Classify64x4", h_Iop_Classify64x4, {Ity_I64,Ity_I64,Ity_V256,Ity_I8}},
	[ INDEX (Iop_Classify64x8)]	= {"Iop_Classify64x8", h_Iop_Classify64x8, {Ity_I64,Ity_I64,Ity_V512,Ity_I8}},
	[ INDEX (Iop_Classify32F0x4)]	= {"Iop_Classify32F0x4", h_Iop_Classify32F0x4, {Ity_I64,Ity_I64,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Classify64F0x2)]	= {"Iop_Classify64F0x2", h_Iop_Classify64F0x2, {Ity_I64,Ity_I64,Ity_V128,Ity_I8}},
	[ INDEX (Iop_VPSHLDW_128)]	= {"Iop_VPSHLDW_128", NULL, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_VPSHLDVD_128)]	= {"Iop_VPSHLDVD_128", NULL, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_VPSHLDVQ_128)]	= {"Iop_VPSHLDVQ_128", NULL, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_VPSHRDVW_128)]	= {"Iop_VPSHRDVW_128", NULL, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_VPSHRDW_128)]	= {"Iop_VPSHRDW_128", NULL, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_VPSHRDVD_128)]	= {"Iop_VPSHRDVD_128", NULL, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_VPSHRDD_128)]	= {"Iop_VPSHRDD_128", NULL, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_VPSHRDVQ_128)]	= {"Iop_VPSHRDVQ_128", NULL, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_VPSHRDQ_128)]	= {"Iop_VPSHRDQ_128", NULL, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_PermI8x16)]	= {"Iop_PermI8x16", h_Iop_PermI8x16, {Ity_V128,Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_PermI8x32)]	= {"Iop_PermI8x32", h_Iop_PermI8x32, {Ity_V256,Ity_V256,Ity_V256,Ity_V256}},
	[ INDEX (Iop_PermI8x64)]	= {"Iop_PermI8x64", h_Iop_PermI8x64, {Ity_V512,Ity_V512,Ity_V512,Ity_V512}},
	[ INDEX (Iop_PermI16x8)]	= {"Iop_PermI16x8", h_Iop_PermI16x8, {Ity_V128,Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_PermI16x16)]	= {"Iop_PermI16x16", h_Iop_PermI16x16, {Ity_V256,Ity_V256,Ity_V256,Ity_V256}},
	[ INDEX (Iop_PermI16x32)]	= {"Iop_PermI16x32", h_Iop_PermI16x32, {Ity_V512,Ity_V512,Ity_V512,Ity_V512}},
	[ INDEX (Iop_PermI32x4)]	= {"Iop_PermI32x4", h_Iop_PermI32x4, {Ity_V128,Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_PermI32x8)]	= {"Iop_PermI32x8", h_Iop_PermI32x8, {Ity_V256,Ity_V256,Ity_V256,Ity_V256}},
	[ INDEX (Iop_PermI32x16)]	= {"Iop_PermI32x16", h_Iop_PermI32x16, {Ity_V512,Ity_V512,Ity_V512,Ity_V512}},
	[ INDEX (Iop_PermI64x2)]	= {"Iop_PermI64x2", h_Iop_PermI64x2, {Ity_V128,Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_PermI64x4)]	= {"Iop_PermI64x4", h_Iop_PermI64x4, {Ity_V256,Ity_V256,Ity_V256,Ity_V256}},
	[ INDEX (Iop_PermI64x8)]	= {"Iop_PermI64x8", h_Iop_PermI64x8, {Ity_V512,Ity_V512,Ity_V512,Ity_V512}},
	[ INDEX (Iop_MULTISHIFTQB)]	= {"Iop_MULTISHIFTQB", h_Iop_MULTISHIFTQB, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_Perm8x32)]	= {"Iop_Perm8x32", h_Iop_Perm8x32, {Ity_V256,Ity_V256,Ity_V256}},
	[ INDEX (Iop_Perm8x64)]	= {"Iop_Perm8x64", h_Iop_Perm8x64, {Ity_V512,Ity_V512,Ity_V512}},
	[ INDEX (Iop_Perm16x8)]	= {"Iop_Perm16x8", h_Iop_Perm16x8, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_Perm16x16)]	= {"Iop_Perm16x16", h_Iop_Perm16x16, {Ity_V256,Ity_V256,Ity_V256}},
	[ INDEX (Iop_Perm16x32)]	= {"Iop_Perm16x32", h_Iop_Perm16x32, {Ity_V512,Ity_V512,Ity_V512}},
	[ INDEX (Iop_VPSHUFBITQMB_128)]	= {"Iop_VPSHUFBITQMB_128", h_Iop_VPSHUFBITQMB_128, {Ity_I16,Ity_V128,Ity_V128}},
	[ INDEX (Iop_VPSHUFBITQMB_256)]	= {"Iop_VPSHUFBITQMB_256", h_Iop_VPSHUFBITQMB_256, {Ity_I32,Ity_V256,Ity_V256}},
	[ INDEX (Iop_VPSHUFBITQMB_512)]	= {"Iop_VPSHUFBITQMB_512", h_Iop_VPSHUFBITQMB_512, {Ity_I64,Ity_V512,Ity_V512}},
	[ INDEX (Iop_PMADD52LUQ )]	= {"Iop_PMADD52LUQ ", h_Iop_PMADD52LUQ , {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_PMADD52HUQ )]	= {"Iop_PMADD52HUQ ", h_Iop_PMADD52HUQ , {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_Cmp32Fx4)]	= {"Iop_Cmp32Fx4", h_Iop_Cmp32Fx4, {Ity_I64,Ity_I64,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Cmp32Fx8)]	= {"Iop_Cmp32Fx8", h_Iop_Cmp32Fx8, {Ity_I64,Ity_I64,Ity_V256,Ity_V256,Ity_I8}},
	[ INDEX (Iop_Cmp32Fx16)]	= {"Iop_Cmp32Fx16", h_Iop_Cmp32Fx16, {Ity_I64,Ity_I64,Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_Cmp64Fx2)]	= {"Iop_Cmp64Fx2", h_Iop_Cmp64Fx2, {Ity_I64,Ity_I64,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_Cmp64Fx4)]	= {"Iop_Cmp64Fx4", h_Iop_Cmp64Fx4, {Ity_I64,Ity_I64,Ity_V256,Ity_V256,Ity_I8}},
	[ INDEX (Iop_Cmp64Fx8)]	= {"Iop_Cmp64Fx8", h_Iop_Cmp64Fx8, {Ity_I64,Ity_I64,Ity_V512,Ity_V512,Ity_I8}},
	[ INDEX (Iop_CfD32x4)]	= {"Iop_CfD32x4", h_Iop_CfD32x4, {Ity_V128,Ity_V128}},
	[ INDEX (Iop_CfD32x8)]	= {"Iop_CfD32x8", h_Iop_CfD32x8, {Ity_V256,Ity_V256}},
	[ INDEX (Iop_CfD32x16)]	= {"Iop_CfD32x16", h_Iop_CfD32x16, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_CfD64x2)]	= {"Iop_CfD64x2", h_Iop_CfD64x2, {Ity_V128,Ity_V128}},
	[ INDEX (Iop_CfD64x4)]	= {"Iop_CfD64x4", h_Iop_CfD64x4, {Ity_V256,Ity_V256}},
	[ INDEX (Iop_CfD64x8)]	= {"Iop_CfD64x8", h_Iop_CfD64x8, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_Exp32x16)]	= {"Iop_Exp32x16", h_Iop_Exp32x16, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_Exp64x8)]	= {"Iop_Exp64x8", h_Iop_Exp64x8, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_Recip28_32x16)]	= {"Iop_Recip28_32x16", h_Iop_Recip28_32x16, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_Recip28_64x8)]	= {"Iop_Recip28_64x8", h_Iop_Recip28_64x8, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_Recip28_32F0x4)]	= {"Iop_Recip28_32F0x4", h_Iop_Recip28_32F0x4, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_Recip28_64F0x2)]	= {"Iop_Recip28_64F0x2", h_Iop_Recip28_64F0x2, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_RSqrt28_32x16)]	= {"Iop_RSqrt28_32x16", h_Iop_RSqrt28_32x16, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_RSqrt28_64x8)]	= {"Iop_RSqrt28_64x8", h_Iop_RSqrt28_64x8, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_RSqrt28_32F0x4)]	= {"Iop_RSqrt28_32F0x4", h_Iop_RSqrt28_32F0x4, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_RSqrt28_64F0x2)]	= {"Iop_RSqrt28_64F0x2", h_Iop_RSqrt28_64F0x2, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_Gfni)]	= {"Iop_Gfni", NULL, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_GfniMult)]	= {"Iop_GfniMult", NULL, {Ity_V128,Ity_V128,Ity_V128}},
	[ INDEX (Iop_GfniInv)]	= {"Iop_GfniInv", NULL, {Ity_V128,Ity_V128,Ity_V128,Ity_I8}},
	[ INDEX (Iop_OrV512)]	= {"Iop_OrV512", NULL, {Ity_V512,Ity_V512,Ity_V512}},
	[ INDEX (Iop_AndV512)]	= {"Iop_AndV512", NULL, {Ity_V512,Ity_V512,Ity_V512}},
	[ INDEX (Iop_NotV512)]	= {"Iop_NotV512", NULL, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_CmpNEZ32x16)]	= {"Iop_CmpNEZ32x16", NULL, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_CmpNEZ64x8)]	= {"Iop_CmpNEZ64x8", NULL, {Ity_V512,Ity_V512}},
	[ INDEX (Iop_V256HLtoV512)]	= {"Iop_V256HLtoV512", NULL, {Ity_V512,Ity_V256,Ity_V256}},
	[ INDEX (Iop_V512toV256_0)]	= {"Iop_V512toV256_0", NULL, {Ity_V256,Ity_V512}},
	[ INDEX (Iop_V512toV256_1)]	= {"Iop_V512toV256_1", NULL, {Ity_V256,Ity_V512}},
	[ INDEX (Iop_V512to64_0)]	= {"Iop_V512to64_0", NULL, {Ity_I64,Ity_V512}},
	[ INDEX (Iop_V512to64_1)]	= {"Iop_V512to64_1", NULL, {Ity_I64,Ity_V512}},
	[ INDEX (Iop_V512to64_2)]	= {"Iop_V512to64_2", NULL, {Ity_I64,Ity_V512}},
	[ INDEX (Iop_V512to64_3)]	= {"Iop_V512to64_3", NULL, {Ity_I64,Ity_V512}},
	[ INDEX (Iop_V512to64_4)]	= {"Iop_V512to64_4", NULL, {Ity_I64,Ity_V512}},
	[ INDEX (Iop_V512to64_5)]	= {"Iop_V512to64_5", NULL, {Ity_I64,Ity_V512}},
	[ INDEX (Iop_V512to64_6)]	= {"Iop_V512to64_6", NULL, {Ity_I64,Ity_V512}},
	[ INDEX (Iop_V512to64_7)]	= {"Iop_V512to64_7", NULL, {Ity_I64,Ity_V512}},
	[ INDEX (Iop_ExpandBitsToInt)]	= {"Iop_ExpandBitsToInt", h_Iop_ExpandBitsToInt, {Ity_I64,Ity_I64,Ity_I8}},
	[ INDEX (Iop_Compress32x4)]	= {"Iop_Compress32x4", h_Iop_Compress32x4, {Ity_V128,Ity_V128,Ity_V128,Ity_I64,Ity_I8}},
	[ INDEX (Iop_Compress32x8)]	= {"Iop_Compress32x8", h_Iop_Compress32x8, {Ity_V256,Ity_V256,Ity_V256,Ity_I64,Ity_I8}},
	[ INDEX (Iop_Compress32x16)]	= {"Iop_Compress32x16", h_Iop_Compress32x16, {Ity_V512,Ity_V512,Ity_V512,Ity_I64,Ity_I8}},
	[ INDEX (Iop_Compress64x2)]	= {"Iop_Compress64x2", h_Iop_Compress64x2, {Ity_V128,Ity_V128,Ity_V128,Ity_I64,Ity_I8}},
	[ INDEX (Iop_Compress64x4)]	= {"Iop_Compress64x4", h_Iop_Compress64x4, {Ity_V256,Ity_V256,Ity_V256,Ity_I64,Ity_I8}},
	[ INDEX (Iop_Compress64x8)]	= {"Iop_Compress64x8", h_Iop_Compress64x8, {Ity_V512,Ity_V512,Ity_V512,Ity_I64,Ity_I8}},
	[ INDEX (Iop_Expand32x4)]	= {"Iop_Expand32x4", h_Iop_Expand32x4, {Ity_V128,Ity_V128,Ity_V128,Ity_I64,Ity_I8}},
	[ INDEX (Iop_Expand32x8)]	= {"Iop_Expand32x8", h_Iop_Expand32x8, {Ity_V256,Ity_V256,Ity_V256,Ity_I64,Ity_I8}},
	[ INDEX (Iop_Expand32x16)]	= {"Iop_Expand32x16", h_Iop_Expand32x16, {Ity_V512,Ity_V512,Ity_V512,Ity_I64,Ity_I8}},
	[ INDEX (Iop_Expand64x2)]	= {"Iop_Expand64x2", h_Iop_Expand64x2, {Ity_V128,Ity_V128,Ity_V128,Ity_I64,Ity_I8}},
	[ INDEX (Iop_Expand64x4)]	= {"Iop_Expand64x4", h_Iop_Expand64x4, {Ity_V256,Ity_V256,Ity_V256,Ity_I64,Ity_I8}},
	[ INDEX (Iop_Expand64x8)]	= {"Iop_Expand64x8", h_Iop_Expand64x8, {Ity_V512,Ity_V512,Ity_V512,Ity_I64,Ity_I8}},
	[ INDEX (Iop_I32UtoF32_SKX)]	= {"Iop_I32UtoF32_SKX", h_Iop_I32UtoF32_SKX, {Ity_I32,Ity_I32,Ity_I32}},
	[ INDEX (Iop_I64UtoF64_SKX)]	= {"Iop_I64UtoF64_SKX", h_Iop_I64UtoF64_SKX, {Ity_I64,Ity_I32,Ity_I64}},
	[ INDEX (Iop_F32toI32U_SKX)]	= {"Iop_F32toI32U_SKX", h_Iop_F32toI32U_SKX, {Ity_I32,Ity_I32,Ity_I32}},
	[ INDEX (Iop_F64toI32U_SKX)]	= {"Iop_F64toI32U_SKX", h_Iop_F64toI32U_SKX, {Ity_I32,Ity_I32,Ity_I64}},
	[ INDEX (Iop_F64toI64U_SKX)]	= {"Iop_F64toI64U_SKX", h_Iop_F64toI64U_SKX, {Ity_I64,Ity_I32,Ity_I64}},
	[ INDEX (Iop_PrintI64)]	= {"Iop_PrintI64", h_Iop_PrintI64, {Ity_I64,Ity_I64}},
};
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif
#endif /* ndef __HOST_AVX512_H */
#endif /* ndef AVX_512*/
