#ifdef AVX_512
#ifndef __VEX_HOST_GENERIC_AVX512_H
#define __VEX_HOST_GENERIC_AVX512_H

/* This file is auto-generated by "filegen" script */
/* DO NOT MODIFY */

/*
   This file is part of Valgrind, a dynamic binary instrumentation
   framework.

   Copyright (C) 2021 Intel Corporation 
      tatyana.a.volnina@intel.com

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License as
   published by the Free Software Foundation; either version 2 of the
   License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, see <http://www.gnu.org/licenses/>.

   The GNU General Public License is contained in the file COPYING.
*/

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wattributes"
#endif
#include <libvex_basictypes.h>
VEX_REGPARM(3) void h_Iop_RoundScale32x16 (V512*,V512*,UInt);
VEX_REGPARM(3) void h_Iop_RoundScale64x8 (V512*,V512*,UInt);
VEX_REGPARM(3) void h_Iop_RoundScale32F0x4 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_RoundScale64F0x2 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_Perm32x16 (V512*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_Perm64x4 (V256*,V256*,V256*);
VEX_REGPARM(3) void h_Iop_Perm64x8 (V512*,V512*,V512*);
VEX_REGPARM(4) void h_Iop_Cmp32Ux4 (ULong*,V128*,V128*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp32Ux8 (ULong*,V256*,V256*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp32Ux16 (ULong*,V512*,V512*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp64Ux2 (ULong*,V128*,V128*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp64Ux4 (ULong*,V256*,V256*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp64Ux8 (ULong*,V512*,V512*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp32Sx4 (ULong*,V128*,V128*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp32Sx8 (ULong*,V256*,V256*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp32Sx16 (ULong*,V512*,V512*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp64Sx2 (ULong*,V128*,V128*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp64Sx4 (ULong*,V256*,V256*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp64Sx8 (ULong*,V512*,V512*,UInt);
VEX_REGPARM(2) void h_Iop_16Sto8x8 (ULong*,V128*);
VEX_REGPARM(4) void h_Iop_Ternlog32x16 (V512*,V512*,V512*,UInt);
VEX_REGPARM(4) void h_Iop_Ternlog64x8 (V512*,V512*,V512*,UInt);
VEX_REGPARM(3) void h_Iop_Test8x16 (ULong*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_Test8x32 (ULong*,V256*,V256*);
VEX_REGPARM(3) void h_Iop_Test8x64 (ULong*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_Test16x8 (ULong*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_Test16x16 (ULong*,V256*,V256*);
VEX_REGPARM(3) void h_Iop_Test16x32 (ULong*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_GetMant32x16 (V512*,V512*,UInt);
VEX_REGPARM(3) void h_Iop_GetMant64x8 (V512*,V512*,UInt);
VEX_REGPARM(3) void h_Iop_TestN8x16 (ULong*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_TestN8x32 (ULong*,V256*,V256*);
VEX_REGPARM(3) void h_Iop_TestN8x64 (ULong*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_TestN16x8 (ULong*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_TestN16x16 (ULong*,V256*,V256*);
VEX_REGPARM(3) void h_Iop_TestN16x32 (ULong*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_Test32x4 (ULong*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_Test32x8 (ULong*,V256*,V256*);
VEX_REGPARM(3) void h_Iop_Test32x16 (ULong*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_Test64x2 (ULong*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_Test64x4 (ULong*,V256*,V256*);
VEX_REGPARM(3) void h_Iop_Test64x8 (ULong*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_GetMant32F0x4 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_GetMant64F0x2 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_TestN32x4 (ULong*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_TestN32x8 (ULong*,V256*,V256*);
VEX_REGPARM(3) void h_Iop_TestN32x16 (ULong*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_TestN64x2 (ULong*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_TestN64x4 (ULong*,V256*,V256*);
VEX_REGPARM(3) void h_Iop_TestN64x8 (ULong*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_ExpandBitsToV128 (V128*,ULong,UInt);
VEX_REGPARM(3) void h_Iop_ExpandBitsToV256 (V256*,ULong,UInt);
VEX_REGPARM(3) void h_Iop_ExpandBitsToV512 (V512*,ULong,UInt);
VEX_REGPARM(3) void h_Iop_Scale32x16 (V512*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_Scale64x8 (V512*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_Scale32F0x4 (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_Scale64F0x2 (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_Min64Sx8 (V512*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_Min64Ux8 (V512*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_Max64Sx8 (V512*,V512*,V512*);
VEX_REGPARM(4) void h_Iop_Cmp8Ux16 (ULong*,V128*,V128*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp8Ux32 (ULong*,V256*,V256*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp8Ux64 (ULong*,V512*,V512*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp16Ux8 (ULong*,V128*,V128*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp16Ux16 (ULong*,V256*,V256*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp16Ux32 (ULong*,V512*,V512*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp8Sx16 (ULong*,V128*,V128*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp8Sx32 (ULong*,V256*,V256*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp8Sx64 (ULong*,V512*,V512*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp16Sx8 (ULong*,V128*,V128*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp16Sx16 (ULong*,V256*,V256*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp16Sx32 (ULong*,V512*,V512*,UInt);
VEX_REGPARM(3) void h_Iop_Max64Ux8 (V512*,V512*,V512*);
VEX_REGPARM(2) void h_Iop_ExtractExp32x16 (V512*,V512*);
VEX_REGPARM(2) void h_Iop_ExtractExp64x8 (V512*,V512*);
VEX_REGPARM(3) void h_Iop_VDBPSADBW (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_ExtractExp32F0x4 (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_ExtractExp64F0x2 (V128*,V128*,V128*);
VEX_REGPARM(2) void h_Iop_Recip14_32x16 (V512*,V512*);
VEX_REGPARM(2) void h_Iop_Recip14_64x8 (V512*,V512*);
VEX_REGPARM(3) void h_Iop_Recip14_32F0x4 (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_Recip14_64F0x2 (V128*,V128*,V128*);
VEX_REGPARM(2) void h_Iop_RSqrt14_32x16 (V512*,V512*);
VEX_REGPARM(2) void h_Iop_RSqrt14_64x8 (V512*,V512*);
VEX_REGPARM(3) void h_Iop_RSqrt14_32F0x4 (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_RSqrt14_64F0x2 (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_Range32x4 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_Range64x2 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_DPBUSD (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_Range32F0x4 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_Range64F0x2 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_DPBUSDS (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_DPWSSD (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_DPWSSDS (V128*,V128*,V128*);
VEX_REGPARM(4) void h_Iop_FixupImm32x16 (V512*,V512*,V512*,UInt);
VEX_REGPARM(4) void h_Iop_FixupImm64x8 (V512*,V512*,V512*,UInt);
VEX_REGPARM(2) void h_Iop_PopCount8x16 (V128*,V128*);
VEX_REGPARM(4) void h_Iop_FixupImm32F0x4 (V128*,V128*,V128*,UInt);
VEX_REGPARM(4) void h_Iop_FixupImm64F0x2 (V128*,V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_Reduce32x4 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_Reduce64x2 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_Reduce32F0x4 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_Reduce64F0x2 (V128*,V128*,UInt);
VEX_REGPARM(2) void h_Iop_Compress8x16 (V128*,V128*);
VEX_REGPARM(2) void h_Iop_Compress16x8 (V128*,V128*);
VEX_REGPARM(3) void h_Iop_Classify32x4 (ULong*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_Classify32x8 (ULong*,V256*,UInt);
VEX_REGPARM(3) void h_Iop_Classify32x16 (ULong*,V512*,UInt);
VEX_REGPARM(3) void h_Iop_Classify64x2 (ULong*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_Classify64x4 (ULong*,V256*,UInt);
VEX_REGPARM(3) void h_Iop_Classify64x8 (ULong*,V512*,UInt);
VEX_REGPARM(3) void h_Iop_Classify32F0x4 (ULong*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_Classify64F0x2 (ULong*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_VPSHLDW_128 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_VPSHLDVD_128 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_VPSHLDVQ_128 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_VPSHRDVW_128 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_VPSHRDW_128 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_ShrV128 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_ShlV128 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_VPSHRDVD_128 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_VPSHRDD_128 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_VPSHRDVQ_128 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_VPSHRDQ_128 (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_PermI8x16 (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_PermI8x32 (V256*,V256*,V256*);
VEX_REGPARM(3) void h_Iop_PermI8x64 (V512*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_PermI16x8 (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_PermI16x16 (V256*,V256*,V256*);
VEX_REGPARM(3) void h_Iop_PermI16x32 (V512*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_PermI32x4 (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_PermI32x8 (V256*,V256*,V256*);
VEX_REGPARM(3) void h_Iop_PermI32x16 (V512*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_PermI64x2 (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_PermI64x4 (V256*,V256*,V256*);
VEX_REGPARM(3) void h_Iop_PermI64x8 (V512*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_MULTISHIFTQB (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_Perm8x32 (V256*,V256*,V256*);
VEX_REGPARM(3) void h_Iop_Perm8x64 (V512*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_Perm16x8 (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_Perm16x16 (V256*,V256*,V256*);
VEX_REGPARM(3) void h_Iop_Perm16x32 (V512*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_VPSHUFBITQMB_128 (UInt*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_VPSHUFBITQMB_256 (UInt*,V256*,V256*);
VEX_REGPARM(3) void h_Iop_VPSHUFBITQMB_512 (ULong*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_PMADD52LUQ  (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_PMADD52HUQ  (V128*,V128*,V128*);
VEX_REGPARM(4) void h_Iop_Cmp32Fx4 (ULong*,V128*,V128*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp32Fx8 (ULong*,V256*,V256*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp32Fx16 (ULong*,V512*,V512*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp64Fx2 (ULong*,V128*,V128*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp64Fx4 (ULong*,V256*,V256*,UInt);
VEX_REGPARM(4) void h_Iop_Cmp64Fx8 (ULong*,V512*,V512*,UInt);
VEX_REGPARM(2) void h_Iop_CfD32x4 (V128*,V128*);
VEX_REGPARM(2) void h_Iop_CfD32x8 (V256*,V256*);
VEX_REGPARM(2) void h_Iop_CfD32x16 (V512*,V512*);
VEX_REGPARM(2) void h_Iop_CfD64x2 (V128*,V128*);
VEX_REGPARM(2) void h_Iop_CfD64x4 (V256*,V256*);
VEX_REGPARM(2) void h_Iop_CfD64x8 (V512*,V512*);
VEX_REGPARM(2) void h_Iop_Exp32x16 (V512*,V512*);
VEX_REGPARM(2) void h_Iop_Exp64x8 (V512*,V512*);
VEX_REGPARM(2) void h_Iop_Recip28_32x16 (V512*,V512*);
VEX_REGPARM(2) void h_Iop_Recip28_64x8 (V512*,V512*);
VEX_REGPARM(3) void h_Iop_Recip28_32F0x4 (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_Recip28_64F0x2 (V128*,V128*,V128*);
VEX_REGPARM(2) void h_Iop_RSqrt28_32x16 (V512*,V512*);
VEX_REGPARM(2) void h_Iop_RSqrt28_64x8 (V512*,V512*);
VEX_REGPARM(3) void h_Iop_RSqrt28_32F0x4 (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_RSqrt28_64F0x2 (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_Gfni (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_GfniMult (V128*,V128*,V128*);
VEX_REGPARM(3) void h_Iop_GfniInv (V128*,V128*,UInt);
VEX_REGPARM(3) void h_Iop_OrV512 (V512*,V512*,V512*);
VEX_REGPARM(3) void h_Iop_AndV512 (V512*,V512*,V512*);
VEX_REGPARM(2) void h_Iop_NotV512 (V512*,V512*);
VEX_REGPARM(2) void h_Iop_CmpNEZ32x16 (V512*,V512*);
VEX_REGPARM(2) void h_Iop_CmpNEZ64x8 (V512*,V512*);
VEX_REGPARM(3) void h_Iop_V256HLtoV512 (V512*,V256*,V256*);
VEX_REGPARM(2) void h_Iop_V512toV256_0 (V256*,V512*);
VEX_REGPARM(2) void h_Iop_V512toV256_1 (V256*,V512*);
VEX_REGPARM(2) void h_Iop_V512to64_0 (ULong*,V512*);
VEX_REGPARM(2) void h_Iop_V512to64_1 (ULong*,V512*);
VEX_REGPARM(2) void h_Iop_V512to64_2 (ULong*,V512*);
VEX_REGPARM(2) void h_Iop_V512to64_3 (ULong*,V512*);
VEX_REGPARM(2) void h_Iop_V512to64_4 (ULong*,V512*);
VEX_REGPARM(2) void h_Iop_V512to64_5 (ULong*,V512*);
VEX_REGPARM(2) void h_Iop_V512to64_6 (ULong*,V512*);
VEX_REGPARM(2) void h_Iop_V512to64_7 (ULong*,V512*);
VEX_REGPARM(3) void h_Iop_ExpandBitsToInt (ULong*,ULong,UInt);
VEX_REGPARM(4) void h_Iop_Compress32x4 (V128*,V128*,ULong,UInt);
VEX_REGPARM(4) void h_Iop_Compress32x8 (V256*,V256*,ULong,UInt);
VEX_REGPARM(4) void h_Iop_Compress32x16 (V512*,V512*,ULong,UInt);
VEX_REGPARM(4) void h_Iop_Compress64x2 (V128*,V128*,ULong,UInt);
VEX_REGPARM(4) void h_Iop_Compress64x4 (V256*,V256*,ULong,UInt);
VEX_REGPARM(4) void h_Iop_Compress64x8 (V512*,V512*,ULong,UInt);
VEX_REGPARM(4) void h_Iop_Expand32x4 (V128*,V128*,ULong,UInt);
VEX_REGPARM(4) void h_Iop_Expand32x8 (V256*,V256*,ULong,UInt);
VEX_REGPARM(4) void h_Iop_Expand32x16 (V512*,V512*,ULong,UInt);
VEX_REGPARM(4) void h_Iop_Expand64x2 (V128*,V128*,ULong,UInt);
VEX_REGPARM(4) void h_Iop_Expand64x4 (V256*,V256*,ULong,UInt);
VEX_REGPARM(4) void h_Iop_Expand64x8 (V512*,V512*,ULong,UInt);
VEX_REGPARM(3) void h_Iop_I32UtoF32_SKX (UInt*,UInt,UInt);
VEX_REGPARM(3) void h_Iop_I64UtoF64_SKX (ULong*,UInt,ULong);
VEX_REGPARM(3) void h_Iop_F32toI32U_SKX (UInt*,UInt,UInt);
VEX_REGPARM(3) void h_Iop_F64toI32U_SKX (UInt*,UInt,ULong);
VEX_REGPARM(3) void h_Iop_F64toI64U_SKX (ULong*,UInt,ULong);
VEX_REGPARM(2) void h_Iop_Clz32 (UInt*,UInt);
VEX_REGPARM(2) void h_Iop_PrintI64 (ULong*,ULong);

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif
#endif /* ndef __VEX_HOST_GENERIC_AVX512_H */
#endif /* ndef AVX_512*/
