name: Build

on:
  push:
    paths:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install gmake
        run: brew install make
        if: ${{ contains(matrix.os, 'macos') }}
      - run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          nmake /f Makefile-msvc all
        name: Build VEX (windows)
        shell: cmd
        if: ${{ contains(matrix.os, 'windows') }}
      - run: gmake -f Makefile-gcc -j 2 all
        name: Build VEX (nix)
        if: ${{ ! contains(matrix.os, 'windows') }}
